
version: '3.9'
services:
  mysql-db:
    image: mysql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_DATABASE=mysql-db
      - MYSQL_USER=root
      - MYSQL_PASSWORD=root
      - MYSQL_ROOT_PASSWORD=root
    networks:
      - express-network

networks:
  express-network:
